- name: Ansble Sample 1
  become: yes
  hosts: vagrant
  roles:
    - base
    - nginx
    - rbenv
  tasks:
    - name: git clone app
      git:
        repo: git@github.com:sinshutu/learn-provisioning.git
